<?php

namespace Database\Seeders;

use App\Models\ProductCategory;
use Illuminate\Database\Seeder;

class ProductCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'Appliances',
            'Art and Paintings',
            'Arts and Crafts',
            'Automotive',
            'Automotive Parts and Accessories',
            'Automotive Tools and Equipment',
            'Baby and Kids Clothing',
            'Baby and Maternity',
            'Baby Care Products',
            'Baby Feeding Supplies',
            'Baby Nursery Furniture',
            'Baby Safety and Health Products',
            'Baby Strollers and Car Seats',
            'Backpacks and Messenger Bags',
            'Bags and Luggage',
            'Bath and Shower Products',
            'Bath Towels and Mats',
            'Bed Sheets and Pillowcases',
            'Bedding and Linens',
            'Beauty and Personal Care',
            'Beauty and Personal Care Appliances',
            'Bicycles and Cycling Accessories',
            'Bird Cages and Accessories',
            'Board Games and Puzzles',
            'Books and Literature',
            'Cameras and Photography',
            'Cameras and Photography Accessories',
            'Car Electronics and Accessories',
            'Car Parts and Accessories',
            'Collectibles and Memorabilia',
            'Construction Tools and Equipment',
            'Cookware and Bakeware',
            'Cosmetics and Makeup',
            'Craft Supplies and DIY',
            'Decorative Garden Items',
            'Desktop and Laptop Computers',
            'Diapers and Wipes',
            'E-books and Digital Publications',
            'Educational and Learning Toys',
            'Educational Books and Toys',
            'Electronics',
            'Electronics Accessories',
            'Electronics Components and Accessories',
            'Exercise and Fitness Machines',
            'Eyewear and Sunglasses',
            'Fiction Books',
            'Fish Supplies and Aquariums',
            'Fitness and Exercise',
            'Fitness Equipment and Accessories',
            'Food and Beverages',
            'Furniture and Cabinet Hardware',
            'Furniture and Decor',
            'Gaming and Entertainment',
            'Gaming Consoles and Accessories',
            'Garden and Outdoor Living',
            'Hair Care Products and Accessories',
            'Handbags and Wallets',
            'Health and Beauty',
            'Home and Kitchen',
            'Home Appliances',
            'Home Décor and Lighting',
            'Home Improvement and Tools',
            'Home Improvement Hardware',
            'Home Security and Surveillance',
            'Industrial and Scientific Equipment',
            'Industrial Machinery and Equipment',
            'Jewelry and Accessories',
            'Jewelry and Accessories for Men and Women',
            'Jewelry Boxes and Organizers',
            'Kids Toys and Games',
            'Kitchen Appliances and Gadgets',
            'Kitchen Gadgets and Utensils',
            'Lab Equipment and Supplies',
            'Lighting Fixtures and Lamps',
            'Makeup and Cosmetic Tools',
            'Maternity Clothing and Accessories',
            "Men's Clothing and Apparel",
            'Model Kits and Building Toys',
            'Motorcycle Gear and Apparel',
            'Motorcycle Parts and Accessories',
            'Musical Accessories and Merchandise',
            'Musical Instrument Accessories',
            'Musical Instruments and Equipment',
            'Non-fiction Books',
            'Office and School Supplies',
            'Original Artwork and Paintings',
            'Outdoor and Camping Gear',
            'Outdoor Clothing and Accessories',
            'Outdoor Play Equipment',
            'Paint and Painting Supplies',
            'Party and Event Supplies',
            'Party Balloons and Banners',
            'Party Supplies and Decor',
            'Party Supplies and Decorations',
            'Personal Care Appliances',
            'Pet Food and Supplies',
            'Pet Grooming and Cleaning Products',
            'Pet Supplies',
            'Pet Toys and Accessories',
            'Planters and Gardening Tools',
            'Power Tools and Hand Tools',
            'Printers and Scanners',
            'Puzzle Games and Brainteasers',
            'Refrigerators and Freezers',
            'Reptile and Amphibian Supplies',
            'School and Office Stationery',
            'Security Systems and Alarms',
            'Shoes and Footwear',
            'Shoes for Men, Women, and Children',
            'Skincare and Beauty Treatments',
            'Small Animal Cages and Habitats',
            'Sports and Outdoors',
            'Sports Apparel and Footwear',
            'Sports Equipment and Gear',
            'Sports Memorabilia and Merchandise',
            'Stationery and Office Supplies',
            'Studio and Recording Equipment',
            'Team Sports Apparel and Shoes',
            'Team Sports Equipment',
            'Tools and Home Improvement',
            'Toys and Games',
            'Travel and Luggage',
            'Travel Bags and Suitcases',
            'Vacuum Cleaners and Floor Care',
            'Vintage and Antique Items',
            'Vintage Collectibles and Memorabilia',
            'Wall Art and Paintings',
            'Washing Machines and Dryers',
            'Water Sports Equipment',
            'Watches and Accessories',
            'Watches and Jewelry Accessories',
            'Watches for Men and Women',
            "Women's Clothing and Apparel",
            'Writing Instruments',
            'Yoga and Pilates Accessories',
        ];

        foreach ($categories as $key => $category) {
            ProductCategory::create([
                'title' => $category,
                'slug'  => str()->slug($category),
            ]);
        }
    }
}
