name: 🚀 Deploy website on push to https://aurora.faisalbhuiyan.com/

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: 🔨 Build Project for Production
        run: |
          npm install
          npm run build

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.production', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-req=php+
      - name: Update Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-req=php+
      # - name: Generate key
      #   run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate:fresh --seed

      # - name: Execute tests (Unit and Feature tests) via Pest PHP
      #   env:
      #     DB_CONNECTION: sqlite
      #     DB_DATABASE: database/database.sqlite
      #   run: vendor/bin/pest

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.faisalbhuiyan.com
          username: aurora@faisalbhuiyan.com
          password: Pa$$w0rd!!!
          port: 21
